In [1]:
# Imports
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Global Settings
pd.set_option("display.max_columns", None)

# 0. Data Loading

In [2]:
curr_path = os.getcwd()
csv_path = curr_path.replace("data_analysis", "datasets/NF-CSE-CIC-IDS2018-v3/NF-CSE-CIC-IDS2018-v3.csv")
timestamp_cols = {"FLOW_START_MILLISECONDS", "FLOW_END_MILLISECONDS"}
chunks = []
for chunk in pd.read_csv(csv_path, chunksize=500_000):
    for col in chunk.select_dtypes(include=["float64"]).columns:
        chunk[col] = chunk[col].astype(np.float32)
    for col in chunk.select_dtypes(include=["int64"]).columns:
        if col in timestamp_cols:
            continue
        elif col == "Label":
            chunk[col] = chunk[col].astype(np.int8)
        else:
            chunk[col] = chunk[col].astype(np.int32)
    chunks.append(chunk)
df = pd.concat(chunks, ignore_index=True)
del chunks

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20115529 entries, 0 to 20115528
Data columns (total 55 columns):
 #   Column                       Dtype
---  ------                       -----
 0   FLOW_START_MILLISECONDS      int64
 1   FLOW_END_MILLISECONDS        int64
 2   IPV4_SRC_ADDR                str
 3   L4_SRC_PORT                  int32
 4   IPV4_DST_ADDR                str
 5   L4_DST_PORT                  int32
 6   PROTOCOL                     int32
 7   L7_PROTO                     int32
 8   IN_BYTES                     int32
 9   IN_PKTS                      int32
 10  OUT_BYTES                    int32
 11  OUT_PKTS                     int32
 12  TCP_FLAGS                    int32
 13  CLIENT_TCP_FLAGS             int32
 14  SERVER_TCP_FLAGS             int32
 15  FLOW_DURATION_MILLISECONDS   int32
 16  DURATION_IN                  int32
 17  DURATION_OUT                 int32
 18  MIN_TTL                      int32
 19  MAX_TTL                      int32
 20  LONGEST_FLOW_PKT             int32
 21  SHORTEST_FLOW_PKT            int32
 22  MIN_IP_PKT_LEN               int32
 23  MAX_IP_PKT_LEN               int32
 24  SRC_TO_DST_SECOND_BYTES      int32
 25  DST_TO_SRC_SECOND_BYTES      int32
 26  RETRANSMITTED_IN_BYTES       int32
 27  RETRANSMITTED_IN_PKTS        int32
 28  RETRANSMITTED_OUT_BYTES      int32
 29  RETRANSMITTED_OUT_PKTS       int32
 30  SRC_TO_DST_AVG_THROUGHPUT    int32
 31  DST_TO_SRC_AVG_THROUGHPUT    int32
 32  NUM_PKTS_UP_TO_128_BYTES     int32
 33  NUM_PKTS_128_TO_256_BYTES    int32
 34  NUM_PKTS_256_TO_512_BYTES    int32
 35  NUM_PKTS_512_TO_1024_BYTES   int32
 36  NUM_PKTS_1024_TO_1514_BYTES  int32
 37  TCP_WIN_MAX_IN               int32
 38  TCP_WIN_MAX_OUT              int32
 39  ICMP_TYPE                    int32
 40  ICMP_IPV4_TYPE               int32
 41  DNS_QUERY_ID                 int32
 42  DNS_QUERY_TYPE               int32
 43  DNS_TTL_ANSWER               int32
 44  FTP_COMMAND_RET_CODE         int32
 45  SRC_TO_DST_IAT_MIN           int32
 46  SRC_TO_DST_IAT_MAX           int32
 47  SRC_TO_DST_IAT_AVG           int32
 48  SRC_TO_DST_IAT_STDDEV        int32
 49  DST_TO_SRC_IAT_MIN           int32
 50  DST_TO_SRC_IAT_MAX           int32
 51  DST_TO_SRC_IAT_AVG           int32
 52  DST_TO_SRC_IAT_STDDEV        int32
 53  Label                        int8
 54  Attack                       str
dtypes: int32(49), int64(2), int8(1), str(3)
memory usage: 4.4 GB

# 1. Data Overview

In [3]:
df.head()

,FLOW_START_MILLISECONDS,FLOW_END_MILLISECONDS,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,SRC_TO_DST_IAT_MIN,SRC_TO_DST_IAT_MAX,SRC_TO_DST_IAT_AVG,SRC_TO_DST_IAT_STDDEV,DST_TO_SRC_IAT_MIN,DST_TO_SRC_IAT_MAX,DST_TO_SRC_IAT_AVG,DST_TO_SRC_IAT_STDDEV,Label,Attack
0,1518611287705,1518611287705,172.31.0.2,53,172.31.66.58,63593,17,5,156,1,0,0,0,0,0,1,0,0,0,0,156,156,0,156,0,1,0,0,0,0,1248000,0,0,1,0,0,0,0,0,0,0,45856,1,60,0,0,0,0,0,0,0,0,0,0,Benign
1,1518611287743,1518611290747,172.31.66.58,56163,239.255.255.250,1900,17,12,805,5,0,0,0,0,0,3003,3003,0,1,1,161,161,0,161,0,0,0,0,0,0,2143,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,2793,750,1182,0,0,0,0,0,Benign
2,1518611288143,1518611300202,172.31.66.46,62388,239.255.255.250,1900,17,12,1288,8,0,0,0,0,0,12058,12058,0,1,1,161,161,0,161,0,0,0,0,0,0,854,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,3016,1722,1436,0,0,0,0,0,Benign
3,1518611288165,1518611336194,0.0.0.0,546,0.0.0.0,547,17,103,393,3,0,0,0,0,0,48029,48029,0,1,1,131,131,0,131,0,0,0,0,0,0,65,0,0,3,0,0,0,0,0,0,0,0,0,0,0,16014,32014,24014,8000,0,0,0,0,0,Benign
4,1518611288175,1518611288176,172.31.66.46,49187,169.254.169.254,80,6,7,373,5,700,5,27,27,27,1,0,0,128,128,528,40,40,528,700,373,0,0,0,0,1492000,2800000,8,1,0,1,0,8192,17922,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Benign

In [4]:
df.tail()

,FLOW_START_MILLISECONDS,FLOW_END_MILLISECONDS,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,SRC_TO_DST_IAT_MIN,SRC_TO_DST_IAT_MAX,SRC_TO_DST_IAT_AVG,SRC_TO_DST_IAT_STDDEV,DST_TO_SRC_IAT_MIN,DST_TO_SRC_IAT_MAX,DST_TO_SRC_IAT_AVG,DST_TO_SRC_IAT_STDDEV,Label,Attack
20115524,1519334572956,1519334662435,52.14.77.172,1024,172.31.69.28,500,17,79,3168,6,0,0,0,0,0,89479,89479,0,62,62,528,528,0,528,0,0,0,0,0,0,283,0,0,0,0,6,0,0,0,0,0,0,0,0,0,4000,41989,17895,13724,0,0,0,0,1,Brute_Force_-XSS
20115525,1519334689509,1519334778989,13.58.42.57,1028,172.31.69.28,500,17,79,3168,6,0,0,0,0,0,89479,89479,0,62,62,528,528,0,528,0,0,0,0,0,0,283,0,0,0,0,6,0,0,0,0,0,0,0,0,0,4000,41990,17895,13725,0,0,0,0,1,Brute_Force_-XSS
20115526,1519334738019,1519334827498,52.14.77.172,1024,172.31.69.28,500,17,79,3168,6,0,0,0,0,0,89479,89479,0,62,62,528,528,0,528,0,0,0,0,0,0,283,0,0,0,0,6,0,0,0,0,0,0,0,0,0,4000,41990,17895,13725,0,0,0,0,1,Brute_Force_-XSS
20115527,1519334854572,1519334944052,13.58.42.57,1028,172.31.69.28,500,17,79,3168,6,0,0,0,0,0,89479,89479,0,62,62,528,528,0,528,0,0,0,0,0,0,283,0,0,0,0,6,0,0,0,0,0,0,0,0,0,4000,41990,17895,13725,0,0,0,0,1,Brute_Force_-XSS
20115528,1519334903081,1519334992561,52.14.77.172,1024,172.31.69.28,500,17,79,3168,6,0,0,0,0,0,89479,89479,0,62,62,528,528,0,528,0,0,0,0,0,0,283,0,0,0,0,6,0,0,0,0,0,0,0,0,0,4000,41990,17895,13725,0,0,0,0,1,Brute_Force_-XSS

In [6]:
df.shape

(20115529, 55)

This are the features on the dataset and their description according to the dataset documentation:

| Feature | Description |
| --- | --- |
| IPV4 SRC ADDR | IPv4 source address |
| IPV4 DST ADDR | IPv4 destination address |
| L4 SRC PORT | IPv4 source port number |
| L4 DST PORT | IPv4 destination port number |
| PROTOCOL | IP protocol identifier byte |
| L7 PROTO | Application protocol (numeric) |
| IN BYTES | Incoming number of bytes |
| OUT BYTES | Outgoing number of bytes |
| IN PKTS | Incoming number of packets |
| OUT PKTS | Outgoing number of packets |
| FLOW DURATION MILLISECONDS | Flow duration in milliseconds |
| TCP FLAGS | Cumulative of all TCP flags |
| CLIENT TCP FLAGS | Cumulative of all client TCP flags |
| SERVER TCP FLAGS | Cumulative of all server TCP flags |
| DURATION IN | Client to Server stream duration (msec) |
| DURATION OUT | Client to Server stream duration (msec) |
| MIN TTL | Min flow TTL |
| MAX TTL | Max flow TTL |
| LONGEST FLOW PKT | Longest packet (bytes) of the flow |
| SHORTEST FLOW PKT | Shortest packet (bytes) of the flow |
| MIN IP PKT LEN | Len of the smallest flow IP packet observed |
| MAX IP PKT LEN | Len of the largest flow IP packet observed |
| SRC TO DST SECOND BYTES | Src to dst Bytes/sec |
| DST TO SRC SECOND BYTES | Dst to src Bytes/sec |
| RETRANSMITTED IN BYTES | Number of retransmitted TCP flow bytes (src->dst) |
| RETRANSMITTED IN PKTS | Number of retransmitted TCP flow packets (src->dst) |
| RETRANSMITTED OUT BYTES | Number of retransmitted TCP flow bytes (dst->src) |
| RETRANSMITTED OUT PKTS | Number of retransmitted TCP flow packets (dst->src) |
| SRC TO DST AVG THROUGHPUT | Src to dst average thpt (bps) |
| DST TO SRC AVG THROUGHPUT | Dst to src average thpt (bps) |
| NUM PKTS UP TO 128 BYTES | Packets whose IP size <= 128 |
| NUM PKTS 128 TO 256 BYTES | Packets whose IP size > 128 and <= 256 |
| NUM PKTS 256 TO 512 BYTES | Packets whose IP size > 256 and <= 512 |
| NUM PKTS 512 TO 1024 BYTES | Packets whose IP size > 512 and <= 1024 |
| NUM PKTS 1024 TO 1514 BYTES | Packets whose IP size > 1024 and <= 1514 |
| TCP WIN MAX IN | Max TCP Window (src->dst) |
| TCP WIN MAX OUT | Max TCP Window (dst->src) |
| ICMP TYPE | ICMP Type * 256 + ICMP code |
| ICMP IPV4 TYPE | ICMP Type |
| DNS QUERY ID | DNS query transaction Id |
| DNS QUERY TYPE | DNS query type (e.g., 1=A, 2=NS..) |
| DNS TTL ANSWER | TTL of the first A record (if any) |
| FTP COMMAND RET CODE | FTP client command return code |
| FLOW START MILLISECONDS | Flow start timestamp in milliseconds |
| FLOW END MILLISECONDS | Flow end timestamp in milliseconds |
| SRC TO DST IAT MIN | Minimum IAT (src->dst) |
| SRC TO DST IAT MAX | Maximum IAT (src->dst) |
| SRC TO DST IAT AVG | Average IAT (src->dst) |
| SRC TO DST IAT STDDEV | Standard deviation of IAT (src->dst) |
| DST TO SRC IAT MIN | Minimum IAT (dst->src) |
| DST TO SRC IAT MAX | Maximum IAT (dst->src) |
| DST TO SRC IAT AVG | Average IAT (dst->src) |
| DST TO SRC IAT STDDEV | Standard deviation of IAT (dst->src) |

# 2. Data Quality

In [6]:
df.isnull().sum()

FLOW_START_MILLISECONDS        0
FLOW_END_MILLISECONDS          0
IPV4_SRC_ADDR                  0
L4_SRC_PORT                    0
IPV4_DST_ADDR                  0
L4_DST_PORT                    0
PROTOCOL                       0
L7_PROTO                       0
IN_BYTES                       0
IN_PKTS                        0
OUT_BYTES                      0
OUT_PKTS                       0
TCP_FLAGS                      0
CLIENT_TCP_FLAGS               0
SERVER_TCP_FLAGS               0
FLOW_DURATION_MILLISECONDS     0
DURATION_IN                    0
DURATION_OUT                   0
MIN_TTL                        0
MAX_TTL                        0
LONGEST_FLOW_PKT               0
SHORTEST_FLOW_PKT              0
MIN_IP_PKT_LEN                 0
MAX_IP_PKT_LEN                 0
SRC_TO_DST_SECOND_BYTES        0
DST_TO_SRC_SECOND_BYTES        0
RETRANSMITTED_IN_BYTES         0
RETRANSMITTED_IN_PKTS          0
RETRANSMITTED_OUT_BYTES        0
RETRANSMITTED_OUT_PKTS         0
SRC_TO_DST_AVG_THROUGHPUT      0
DST_TO_SRC_AVG_THROUGHPUT      0
NUM_PKTS_UP_TO_128_BYTES       0
NUM_PKTS_128_TO_256_BYTES      0
NUM_PKTS_256_TO_512_BYTES      0
NUM_PKTS_512_TO_1024_BYTES     0
NUM_PKTS_1024_TO_1514_BYTES    0
TCP_WIN_MAX_IN                 0
TCP_WIN_MAX_OUT                0
ICMP_TYPE                      0
ICMP_IPV4_TYPE                 0
DNS_QUERY_ID                   0
DNS_QUERY_TYPE                 0
DNS_TTL_ANSWER                 0
FTP_COMMAND_RET_CODE           0
SRC_TO_DST_IAT_MIN             0
SRC_TO_DST_IAT_MAX             0
SRC_TO_DST_IAT_AVG             0
SRC_TO_DST_IAT_STDDEV          0
DST_TO_SRC_IAT_MIN             0
DST_TO_SRC_IAT_MAX             0
DST_TO_SRC_IAT_AVG             0
DST_TO_SRC_IAT_STDDEV          0
Label                          0
Attack                         0
dtype: int64

In [7]:
num_duplicates = df.duplicated().sum() 
total_involved = df.duplicated(keep=False).sum()
num_unique_pairs = num_duplicates

print(f"Total rows in dataset: {len(df):,}")
print(f"Rows marked as duplicates: {num_duplicates:,}")
print(f"Total rows involved in duplication: {total_involved:,}")

Total rows in dataset: 20,115,529
Rows marked as duplicates: 628,474
Total rows involved in duplication: 1,256,674

In [ ]:
# Remove duplicates, keeping first occurrence
df_clean = df.drop_duplicates(keep="first")

print(f"After removing duplicates (keep first): {len(df_clean):,} rows")
print(f"Rows removed: {len(df) - len(df_clean):,}")

After removing duplicates (keep first): 19,487,055 rows
Rows removed: 628,474

In [ ]:
df["Attack"].unique()

<StringArray>
[                  'Benign',           'FTP-BruteForce',
           'SSH-Bruteforce',    'DoS_attacks-GoldenEye',
    'DoS_attacks-Slowloris', 'DoS_attacks-SlowHTTPTest',
         'DoS_attacks-Hulk',   'DDoS_attacks-LOIC-HTTP',
     'DDOS_attack-LOIC-UDP',         'DDOS_attack-HOIC',
         'Brute_Force_-Web',         'Brute_Force_-XSS',
            'SQL_Injection',            'Infilteration',
                      'Bot']
Length: 15, dtype: str

In [ ]:
attack_types_original = df["Attack"].value_counts()
attack_types_clean = df_clean["Attack"].value_counts()
attack_types_dif = attack_types_original - attack_types_clean
attack_types_dif_percent = round((attack_types_dif / attack_types_original) * 100, 2)
side_by_side = pd.DataFrame({"With Duplicates": attack_types_original, "Without Duplicates": attack_types_clean, "Difference (%)": attack_types_dif_percent})
print(side_by_side)

                          With Duplicates  Without Duplicates  Difference (%)
Attack
Benign                           17514626            17392754            0.70
Bot                                207703              111460           46.34
Brute_Force_-Web                     1618                1618            0.00
Brute_Force_-XSS                      480                 460            4.17
DDOS_attack-HOIC                  1032311             1032311            0.00
DDOS_attack-LOIC-UDP                 3450                1725           50.00
DDoS_attacks-LOIC-HTTP             288589              288589            0.00
DoS_attacks-GoldenEye               61300               30650           50.00
DoS_attacks-Hulk                   100076              100076            0.00
DoS_attacks-SlowHTTPTest           105550              105550            0.00
DoS_attacks-Slowloris               36040               18020           50.00
FTP-BruteForce                     386720              193360           50.00
Infilteration                      188152              115805           38.45
SQL_Injection                         440                 440            0.00
SSH-Bruteforce                     188474               94237           50.00

In [ ]:
total_rows = len(df)
attack_rows = df[df["Attack"] != "Benign"].shape[0]
benign_rows = df[df["Attack"] == "Benign"].shape[0]
attack_percentage = (attack_rows / total_rows) * 100
benign_percentage = (benign_rows / total_rows) * 100

total_rows_clean = len(df_clean)
attack_rows_clean = df_clean[df_clean["Attack"] != "Benign"].shape[0]
benign_rows_clean = df_clean[df_clean["Attack"] == "Benign"].shape[0]
attack_percentage_clean = (attack_rows_clean / total_rows_clean) * 100
benign_percentage_clean = (benign_rows_clean / total_rows_clean) * 100

comparison_table = pd.DataFrame({
    "Dataset": ["Original", "Cleaned"],
    "Total Rows": [total_rows, total_rows_clean],
    "Attack %": [attack_percentage, attack_percentage_clean],
    "Benign %": [benign_percentage, benign_percentage_clean]
})
print(comparison_table)

    Dataset  Total Rows   Attack %   Benign %
0  Original    20115529  12.929827  87.070173
1   Cleaned    19487055  10.747140  89.252860

# 3. IPs

In [8]:
top_src_ips = df["IPV4_SRC_ADDR"].value_counts().head(10)
top_dst_ips = df["IPV4_DST_ADDR"].value_counts().head(10)
unique_src_ips = df["IPV4_SRC_ADDR"].nunique()
unique_dst_ips = df["IPV4_DST_ADDR"].nunique()

print("Top 10 Source IPs in Original Dataset:")
print(top_src_ips)
print("\nTop 10 Destination IPs in Original Dataset:")
print(top_dst_ips)
print("\nUnique Source IPs and Count:")
print(unique_src_ips)
print("\nUnique Destination IPs and Count:")
print(unique_dst_ips)

Top 10 Source IPs in Original Dataset:
IPV4_SRC_ADDR
18.221.219.4      386720
13.58.98.64       188474
5.101.40.105      138651
18.218.229.235    133850
18.216.200.189    133776
18.219.9.1        132968
18.218.55.126     132355
52.14.136.135     132322
18.218.11.51      132297
18.216.24.42      132066
Name: count, dtype: int64

Top 10 Destination IPs in Original Dataset:
IPV4_DST_ADDR
172.31.0.2         7320073
172.31.69.25       1169767
172.31.69.28       1042284
169.254.169.254     645849
18.219.211.138      207707
0.0.0.0             108126
72.21.91.29         103554
172.31.64.83         93458
172.31.64.103        69017
178.255.83.1         58566
Name: count, dtype: int64

Unique Source IPs and Count:
181876

Unique Destination IPs and Count:
29036

In [10]:
# Check for all the possible subnets in the dataset that start witgh 172.31
list_source = df[df["IPV4_SRC_ADDR"].str.startswith("172.31")]["IPV4_SRC_ADDR"].unique()
list_destination = df[df["IPV4_DST_ADDR"].str.startswith("172.31")]["IPV4_DST_ADDR"].unique()
joined_list = np.union1d(list_source, list_destination)
unique_subnets = set()
for ip in joined_list:
    subnet = ".".join(ip.split(".")[:3]) + ".0/24"
    unique_subnets.add(subnet)
print("Unique subnets containing 172.31:")
for subnet in unique_subnets:
    print(subnet)

Unique subnets containing 172.31:
172.31.69.0/24
172.31.66.0/24
172.31.67.0/24
172.31.68.0/24
172.31.0.0/24
172.31.64.0/24
172.31.65.0/24
172.31.230.0/24

# 4. Client's data construction
## 4.1 Data Cleaning

In [3]:
import networkx as nx
import community as community_louvain
from collections import defaultdict

In [4]:
# FILTER ATTACK WINDOWS
ATTACK_WINDOWS_MS = [
    # (start_ms, end_ms, description)
    # Wed 14-02-2018
    (pd.Timestamp("2018-02-14 10:32").value // 1_000_000, pd.Timestamp("2018-02-14 12:09").value // 1_000_000, "FTP-BruteForce"),
    (pd.Timestamp("2018-02-14 14:01").value // 1_000_000, pd.Timestamp("2018-02-14 15:31").value // 1_000_000, "SSH-BruteForce"),
    # Thu 15-02-2018
    (pd.Timestamp("2018-02-15 09:26").value // 1_000_000, pd.Timestamp("2018-02-15 10:09").value // 1_000_000, "DoS-GoldenEye"),
    (pd.Timestamp("2018-02-15 10:59").value // 1_000_000, pd.Timestamp("2018-02-15 11:40").value // 1_000_000, "DoS-Slowloris"),
    # Fri 16-02-2018
    (pd.Timestamp("2018-02-16 10:12").value // 1_000_000, pd.Timestamp("2018-02-16 11:08").value // 1_000_000, "DoS-SlowHTTPTest"),
    (pd.Timestamp("2018-02-16 13:45").value // 1_000_000, pd.Timestamp("2018-02-16 14:19").value // 1_000_000, "DoS-Hulk"),
    # Tue 20-02-2018
    (pd.Timestamp("2018-02-20 10:12").value // 1_000_000, pd.Timestamp("2018-02-20 11:17").value // 1_000_000, "DDoS-LOIC-HTTP"),
    (pd.Timestamp("2018-02-20 13:13").value // 1_000_000, pd.Timestamp("2018-02-20 13:32").value // 1_000_000, "DDoS-LOIC-UDP"),
    # Wed 21-02-2018
    (pd.Timestamp("2018-02-21 10:09").value // 1_000_000, pd.Timestamp("2018-02-21 10:43").value // 1_000_000, "DDoS-LOIC-UDP-2"),
    (pd.Timestamp("2018-02-21 14:05").value // 1_000_000, pd.Timestamp("2018-02-21 15:05").value // 1_000_000, "DDoS-HOIC"),
    # Thu 22-02-2018
    (pd.Timestamp("2018-02-22 10:17").value // 1_000_000, pd.Timestamp("2018-02-22 11:24").value // 1_000_000, "BruteForce-Web"),
    (pd.Timestamp("2018-02-22 13:50").value // 1_000_000, pd.Timestamp("2018-02-22 14:29").value // 1_000_000, "BruteForce-XSS"),
    (pd.Timestamp("2018-02-22 16:15").value // 1_000_000, pd.Timestamp("2018-02-22 16:29").value // 1_000_000, "SQLi"),
    # Fri 23-02-2018
    (pd.Timestamp("2018-02-23 10:03").value // 1_000_000, pd.Timestamp("2018-02-23 11:03").value // 1_000_000, "BruteForce-Web-2"),
    (pd.Timestamp("2018-02-23 13:00").value // 1_000_000, pd.Timestamp("2018-02-23 14:10").value // 1_000_000, "BruteForce-XSS-2"),
    (pd.Timestamp("2018-02-23 15:05").value // 1_000_000, pd.Timestamp("2018-02-23 15:18").value // 1_000_000, "SQLi-2"),
    # Wed 28-02-2018
    (pd.Timestamp("2018-02-28 10:50").value // 1_000_000, pd.Timestamp("2018-02-28 12:05").value // 1_000_000, "Infiltration-1"),
    (pd.Timestamp("2018-02-28 13:42").value // 1_000_000, pd.Timestamp("2018-02-28 14:40").value // 1_000_000, "Infiltration-2"),
    # Thu 01-03-2018
    (pd.Timestamp("2018-03-01 09:57").value // 1_000_000, pd.Timestamp("2018-03-01 10:55").value // 1_000_000, "Infiltration-3"),
    (pd.Timestamp("2018-03-01 14:00").value // 1_000_000, pd.Timestamp("2018-03-01 15:37").value // 1_000_000, "Infiltration-4"),
    # Fri 02-03-2018
    (pd.Timestamp("2018-03-02 10:11").value // 1_000_000, pd.Timestamp("2018-03-02 11:34").value // 1_000_000, "Bot-1"),
    (pd.Timestamp("2018-03-02 14:24").value // 1_000_000, pd.Timestamp("2018-03-02 15:55").value // 1_000_000, "Bot-2"),
]

attack_mask = pd.Series(False, index=df.index)
for start_ms, end_ms, _ in ATTACK_WINDOWS_MS:
    in_window = (df["FLOW_START_MILLISECONDS"] >= start_ms) & (df["FLOW_START_MILLISECONDS"] <= end_ms)
    attack_mask |= in_window

df_benign = df[~attack_mask].copy()
print(f"Rows after removing attack windows: {len(df_benign):,}  (removed {attack_mask.sum():,})")

Rows after removing attack windows: 17,646,133  (removed 2,469,396)

In [6]:
# KNOWN ATTACKER IPs (exclude from topology analysis)
ATTACKER_IPS = {
    "172.31.70.4", "172.31.70.6", "172.31.70.46", "172.31.70.8",
    "172.31.70.23", "172.31.70.16",
    "18.218.115.60", "18.219.9.1", "18.219.32.43", "18.218.55.126",
    "52.14.136.135", "18.219.5.43", "18.216.200.189", "18.218.229.235",
    "18.218.11.51", "18.216.24.42", "13.58.225.34", "18.219.211.138",
    "13.58.98.64", "18.221.219.4",
}

# Internal subnet prefix
INTERNAL_PREFIX = "172.31."

def is_internal(ip: str) -> bool:
    return ip.startswith(INTERNAL_PREFIX)


# RESTRICT TO INTERNAL TO INTERNAL FLOWS
mask_internal = (
    df_benign["IPV4_SRC_ADDR"].apply(is_internal) &
    df_benign["IPV4_DST_ADDR"].apply(is_internal) &
    ~df_benign["IPV4_SRC_ADDR"].isin(ATTACKER_IPS) &
    ~df_benign["IPV4_DST_ADDR"].isin(ATTACKER_IPS)
)
df_internal = df_benign[mask_internal]
print(f"Internal benign flows: {len(df_internal):,}")

Internal benign flows: 6,600,723

## 4.2 Weighted Communication Graph

In [7]:
# BUILD WEIGHTED COMMUNICATION GRAPH
# Edge weight = number of flows between the pair (undirected)
edge_counts = (
    df_internal
    .groupby(["IPV4_SRC_ADDR", "IPV4_DST_ADDR"])
    .size()
    .reset_index(name="weight")
)

G = nx.Graph()
for _, row in edge_counts.iterrows():
    src, dst, w = row["IPV4_SRC_ADDR"], row["IPV4_DST_ADDR"], row["weight"]
    if G.has_edge(src, dst):
        G[src][dst]["weight"] += w
    else:
        G.add_edge(src, dst, weight=w)

print(f"Graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

Graph: 457 nodes, 1349 edges

In [8]:
# REMOVE GATEWAY / HIGH-DEGREE HUB NODES
# The gateway node connects to every machine and destroys community structure.
# We remove any node whose degree is > 3 standard deviations above the mean.
degrees = dict(G.degree())
deg_values = np.array(list(degrees.values()))
threshold = deg_values.mean() + 3 * deg_values.std()
hubs = [n for n, d in degrees.items() if d > threshold]
print(f"Removing hub nodes (likely gateways/routers): {hubs}")
G.remove_nodes_from(hubs)

Removing hub nodes (likely gateways/routers): ['172.31.0.2', '172.31.64.1', '172.31.64.127', '172.31.65.1', '172.31.65.127', '172.31.66.1', '172.31.66.127', '172.31.67.1', '172.31.67.127']

## 4.3 Community Detection wih Louvain

In [9]:
# COMMUNITY DETECTION (Louvain)
# resolution > 1 → more, smaller communities; < 1 → fewer, larger ones.
# Tune until you get ~6 communities matching the 5 depts + server room.
partition = community_louvain.best_partition(G, weight="weight", resolution=1.0)

communities = defaultdict(list)
for node, comm_id in partition.items():
    communities[comm_id].append(node)

print(f"\nFound {len(communities)} communities:")
for cid, members in sorted(communities.items()):
    print(f"  Community {cid}: {len(members)} IPs → {sorted(members)}")

Found 400 communities:
  Community 0: 1 IPs → ['172.31.64.106']
  Community 1: 1 IPs → ['172.31.64.110']
  Community 2: 1 IPs → ['172.31.64.113']
  Community 3: 1 IPs → ['172.31.64.115']
  Community 4: 1 IPs → ['172.31.64.118']
  Community 5: 1 IPs → ['172.31.64.121']
  Community 6: 1 IPs → ['172.31.64.122']
  Community 7: 1 IPs → ['172.31.64.16']
  Community 8: 1 IPs → ['172.31.64.17']
  Community 9: 1 IPs → ['172.31.64.19']
  Community 10: 1 IPs → ['172.31.64.23']
  Community 11: 1 IPs → ['172.31.64.26']
  Community 12: 1 IPs → ['172.31.64.31']
  Community 13: 1 IPs → ['172.31.64.35']
  Community 14: 1 IPs → ['172.31.64.37']
  Community 15: 1 IPs → ['172.31.64.38']
  Community 16: 1 IPs → ['172.31.64.4']
  Community 17: 1 IPs → ['172.31.64.41']
  Community 18: 1 IPs → ['172.31.64.44']
  Community 19: 1 IPs → ['172.31.64.45']
  Community 20: 1 IPs → ['172.31.64.46']
  Community 21: 1 IPs → ['172.31.64.51']
  Community 22: 1 IPs → ['172.31.64.54']
  Community 23: 1 IPs → ['172.31.64.58']
  Community 24: 1 IPs → ['172.31.64.63']
  Community 25: 1 IPs → ['172.31.64.65']
  Community 26: 1 IPs → ['172.31.64.67']
  Community 27: 1 IPs → ['172.31.64.68']
  Community 28: 1 IPs → ['172.31.64.70']
  Community 29: 1 IPs → ['172.31.64.71']
  Community 30: 1 IPs → ['172.31.64.75']
  Community 31: 1 IPs → ['172.31.64.76']
  Community 32: 1 IPs → ['172.31.64.79']
  Community 33: 1 IPs → ['172.31.64.84']
  Community 34: 1 IPs → ['172.31.64.95']
  Community 35: 1 IPs → ['172.31.64.96']
  Community 36: 1 IPs → ['172.31.64.99']
  Community 37: 1 IPs → ['172.31.65.10']
  Community 38: 1 IPs → ['172.31.65.123']
  Community 39: 1 IPs → ['172.31.65.14']
  Community 40: 1 IPs → ['172.31.65.17']
  Community 41: 1 IPs → ['172.31.65.18']
  Community 42: 1 IPs → ['172.31.65.19']
  Community 43: 1 IPs → ['172.31.65.28']
  Community 44: 1 IPs → ['172.31.65.29']
  Community 45: 1 IPs → ['172.31.65.33']
  Community 46: 1 IPs → ['172.31.65.34']
  Community 47: 1 IPs → ['172.31.65.36']
  Community 48: 1 IPs → ['172.31.65.38']
  Community 49: 1 IPs → ['172.31.65.39']
  Community 50: 1 IPs → ['172.31.65.40']
  Community 51: 1 IPs → ['172.31.65.50']
  Community 52: 1 IPs → ['172.31.65.51']
  Community 53: 1 IPs → ['172.31.65.56']
  Community 54: 1 IPs → ['172.31.65.58']
  Community 55: 1 IPs → ['172.31.65.59']
  Community 56: 1 IPs → ['172.31.65.6']
  Community 57: 1 IPs → ['172.31.65.66']
  Community 58: 1 IPs → ['172.31.65.67']
  Community 59: 1 IPs → ['172.31.65.69']
  Community 60: 1 IPs → ['172.31.65.81']
  Community 61: 1 IPs → ['172.31.65.84']
  Community 62: 1 IPs → ['172.31.65.86']
  Community 63: 1 IPs → ['172.31.65.88']
  Community 64: 1 IPs → ['172.31.65.9']
  Community 65: 1 IPs → ['172.31.65.98']
  Community 66: 1 IPs → ['172.31.65.99']
  Community 67: 1 IPs → ['172.31.66.10']
  Community 68: 1 IPs → ['172.31.66.100']
  Community 69: 1 IPs → ['172.31.66.101']
  Community 70: 1 IPs → ['172.31.66.102']
  Community 71: 1 IPs → ['172.31.66.109']
  Community 72: 1 IPs → ['172.31.66.114']
  Community 73: 1 IPs → ['172.31.66.12']
  Community 74: 1 IPs → ['172.31.66.120']
  Community 75: 1 IPs → ['172.31.66.22']
  Community 76: 1 IPs → ['172.31.66.41']
  Community 77: 1 IPs → ['172.31.66.42']
  Community 78: 1 IPs → ['172.31.66.43']
  Community 79: 1 IPs → ['172.31.66.44']
  Community 80: 1 IPs → ['172.31.66.49']
  Community 81: 1 IPs → ['172.31.66.54']
  Community 82: 1 IPs → ['172.31.66.58']
  Community 83: 1 IPs → ['172.31.66.60']
  Community 84: 1 IPs → ['172.31.66.62']
  Community 85: 1 IPs → ['172.31.66.69']
  Community 86: 1 IPs → ['172.31.66.72']
  Community 87: 1 IPs → ['172.31.66.73']
  Community 88: 1 IPs → ['172.31.66.79']
  Community 89: 1 IPs → ['172.31.66.82']
  Community 90: 1 IPs → ['172.31.66.85']
  Community 91: 1 IPs → ['172.31.66.89']
  Community 92: 1 IPs → ['172.31.66.9']
  Community 93: 1 IPs → ['172.31.66.90']
  Community 94: 1 IPs → ['172.31.66.96']
  Community 95: 1 IPs → ['172.31.67.10']
  Community 96: 1 IPs → ['172.31.67.100']
  Community 97: 1 IPs → ['172.31.67.101']
  Community 98: 1 IPs → ['172.31.67.111']
  Community 99: 1 IPs → ['172.31.67.112']
  Community 100: 1 IPs → ['172.31.67.13']
  Community 101: 1 IPs → ['172.31.67.14']
  Community 102: 1 IPs → ['172.31.67.15']
  Community 103: 1 IPs → ['172.31.67.21']
  Community 104: 1 IPs → ['172.31.67.23']
  Community 105: 1 IPs → ['172.31.67.24']
  Community 106: 1 IPs → ['172.31.67.28']
  Community 107: 1 IPs → ['172.31.67.32']
  Community 108: 1 IPs → ['172.31.67.34']
  Community 109: 1 IPs → ['172.31.67.35']
  Community 110: 1 IPs → ['172.31.67.37']
  Community 111: 1 IPs → ['172.31.67.38']
  Community 112: 1 IPs → ['172.31.67.41']
  Community 113: 1 IPs → ['172.31.67.46']
  Community 114: 1 IPs → ['172.31.67.50']
  Community 115: 1 IPs → ['172.31.67.54']
  Community 116: 1 IPs → ['172.31.67.60']
  Community 117: 1 IPs → ['172.31.67.72']
  Community 118: 1 IPs → ['172.31.67.75']
  Community 119: 1 IPs → ['172.31.67.76']
  Community 120: 1 IPs → ['172.31.67.80']
  Community 121: 1 IPs → ['172.31.67.81']
  Community 122: 1 IPs → ['172.31.67.86']
  Community 123: 1 IPs → ['172.31.67.94']
  Community 124: 13 IPs → ['172.31.69.10', '172.31.69.11', '172.31.69.12', '172.31.69.17', '172.31.69.19', '172.31.69.20', '172.31.69.22', '172.31.69.23', '172.31.69.24', '172.31.69.5', '172.31.69.6', '172.31.69.8', '172.31.69.9']
  Community 125: 11 IPs → ['172.31.69.1', '172.31.69.14', '172.31.69.16', '172.31.69.25', '172.31.69.26', '172.31.69.27', '172.31.69.28', '172.31.69.29', '172.31.69.30', '172.31.69.31', '172.31.69.4']
  Community 126: 2 IPs → ['172.31.230.0', '172.31.64.78']
  Community 127: 1 IPs → ['172.31.64.11']
  Community 128: 1 IPs → ['172.31.64.13']
  Community 129: 1 IPs → ['172.31.64.18']
  Community 130: 1 IPs → ['172.31.64.69']
  Community 131: 1 IPs → ['172.31.64.100']
  Community 132: 1 IPs → ['172.31.64.101']
  Community 133: 1 IPs → ['172.31.64.103']
  Community 134: 1 IPs → ['172.31.64.104']
  Community 135: 1 IPs → ['172.31.64.107']
  Community 136: 1 IPs → ['172.31.64.108']
  Community 137: 1 IPs → ['172.31.64.109']
  Community 138: 1 IPs → ['172.31.64.111']
  Community 139: 1 IPs → ['172.31.64.112']
  Community 140: 1 IPs → ['172.31.64.114']
  Community 141: 1 IPs → ['172.31.64.116']
  Community 142: 1 IPs → ['172.31.64.117']
  Community 143: 1 IPs → ['172.31.64.119']
  Community 144: 1 IPs → ['172.31.64.12']
  Community 145: 1 IPs → ['172.31.64.124']
  Community 146: 1 IPs → ['172.31.64.125']
  Community 147: 1 IPs → ['172.31.64.126']
  Community 148: 1 IPs → ['172.31.64.14']
  Community 149: 1 IPs → ['172.31.64.15']
  Community 150: 1 IPs → ['172.31.64.20']
  Community 151: 1 IPs → ['172.31.64.21']
  Community 152: 1 IPs → ['172.31.64.24']
  Community 153: 1 IPs → ['172.31.64.27']
  Community 154: 1 IPs → ['172.31.64.28']
  Community 155: 1 IPs → ['172.31.64.29']
  Community 156: 1 IPs → ['172.31.64.32']
  Community 157: 1 IPs → ['172.31.64.33']
  Community 158: 1 IPs → ['172.31.64.34']
  Community 159: 1 IPs → ['172.31.64.36']
  Community 160: 1 IPs → ['172.31.64.39']
  Community 161: 1 IPs → ['172.31.64.40']
  Community 162: 1 IPs → ['172.31.64.42']
  Community 163: 1 IPs → ['172.31.64.47']
  Community 164: 1 IPs → ['172.31.64.48']
  Community 165: 1 IPs → ['172.31.64.49']
  Community 166: 1 IPs → ['172.31.64.52']
  Community 167: 1 IPs → ['172.31.64.57']
  Community 168: 1 IPs → ['172.31.64.60']
  Community 169: 1 IPs → ['172.31.64.61']
  Community 170: 1 IPs → ['172.31.64.64']
  Community 171: 1 IPs → ['172.31.64.7']
  Community 172: 1 IPs → ['172.31.64.72']
  Community 173: 1 IPs → ['172.31.64.73']
  Community 174: 1 IPs → ['172.31.64.74']
  Community 175: 1 IPs → ['172.31.64.77']
  Community 176: 1 IPs → ['172.31.64.8']
  Community 177: 1 IPs → ['172.31.64.80']
  Community 178: 1 IPs → ['172.31.64.81']
  Community 179: 1 IPs → ['172.31.64.83']
  Community 180: 1 IPs → ['172.31.64.85']
  Community 181: 1 IPs → ['172.31.64.86']
  Community 182: 1 IPs → ['172.31.64.87']
  Community 183: 1 IPs → ['172.31.64.88']
  Community 184: 1 IPs → ['172.31.64.89']
  Community 185: 1 IPs → ['172.31.64.91']
  Community 186: 1 IPs → ['172.31.64.92']
  Community 187: 1 IPs → ['172.31.64.93']
  Community 188: 1 IPs → ['172.31.64.94']
  Community 189: 1 IPs → ['172.31.64.97']
  Community 190: 1 IPs → ['172.31.64.98']
  Community 191: 1 IPs → ['172.31.65.20']
  Community 192: 1 IPs → ['172.31.65.5']
  Community 193: 1 IPs → ['172.31.65.64']
  Community 194: 1 IPs → ['172.31.65.91']
  Community 195: 1 IPs → ['172.31.65.100']
  Community 196: 1 IPs → ['172.31.65.103']
  Community 197: 1 IPs → ['172.31.65.104']
  Community 198: 1 IPs → ['172.31.65.105']
  Community 199: 1 IPs → ['172.31.65.107']
  Community 200: 1 IPs → ['172.31.65.108']
  Community 201: 1 IPs → ['172.31.65.109']
  Community 202: 1 IPs → ['172.31.65.11']
  Community 203: 1 IPs → ['172.31.65.112']
  Community 204: 1 IPs → ['172.31.65.113']
  Community 205: 1 IPs → ['172.31.65.114']
  Community 206: 1 IPs → ['172.31.65.116']
  Community 207: 1 IPs → ['172.31.65.117']
  Community 208: 1 IPs → ['172.31.65.118']
  Community 209: 1 IPs → ['172.31.65.121']
  Community 210: 1 IPs → ['172.31.65.122']
  Community 211: 1 IPs → ['172.31.65.124']
  Community 212: 1 IPs → ['172.31.65.126']
  Community 213: 1 IPs → ['172.31.65.13']
  Community 214: 1 IPs → ['172.31.65.16']
  Community 215: 1 IPs → ['172.31.65.21']
  Community 216: 1 IPs → ['172.31.65.23']
  Community 217: 1 IPs → ['172.31.65.24']
  Community 218: 1 IPs → ['172.31.65.25']
  Community 219: 1 IPs → ['172.31.65.27']
  Community 220: 1 IPs → ['172.31.65.30']
  Community 221: 1 IPs → ['172.31.65.32']
  Community 222: 1 IPs → ['172.31.65.35']
  Community 223: 1 IPs → ['172.31.65.37']
  Community 224: 1 IPs → ['172.31.65.41']
  Community 225: 1 IPs → ['172.31.65.42']
  Community 226: 1 IPs → ['172.31.65.43']
  Community 227: 1 IPs → ['172.31.65.44']
  Community 228: 1 IPs → ['172.31.65.45']
  Community 229: 1 IPs → ['172.31.65.46']
  Community 230: 1 IPs → ['172.31.65.47']
  Community 231: 1 IPs → ['172.31.65.48']
  Community 232: 1 IPs → ['172.31.65.49']
  Community 233: 1 IPs → ['172.31.65.52']
  Community 234: 1 IPs → ['172.31.65.55']
  Community 235: 1 IPs → ['172.31.65.57']
  Community 236: 1 IPs → ['172.31.65.61']
  Community 237: 1 IPs → ['172.31.65.65']
  Community 238: 1 IPs → ['172.31.65.68']
  Community 239: 1 IPs → ['172.31.65.70']
  Community 240: 1 IPs → ['172.31.65.71']
  Community 241: 1 IPs → ['172.31.65.72']
  Community 242: 1 IPs → ['172.31.65.73']
  Community 243: 1 IPs → ['172.31.65.75']
  Community 244: 1 IPs → ['172.31.65.76']
  Community 245: 1 IPs → ['172.31.65.77']
  Community 246: 1 IPs → ['172.31.65.78']
  Community 247: 1 IPs → ['172.31.65.79']
  Community 248: 1 IPs → ['172.31.65.8']
  Community 249: 1 IPs → ['172.31.65.80']
  Community 250: 1 IPs → ['172.31.65.82']
  Community 251: 1 IPs → ['172.31.65.83']
  Community 252: 1 IPs → ['172.31.65.85']
  Community 253: 1 IPs → ['172.31.65.87']
  Community 254: 1 IPs → ['172.31.65.89']
  Community 255: 1 IPs → ['172.31.65.90']
  Community 256: 1 IPs → ['172.31.65.93']
  Community 257: 1 IPs → ['172.31.65.96']
  Community 258: 1 IPs → ['172.31.66.121']
  Community 259: 1 IPs → ['172.31.66.25']
  Community 260: 1 IPs → ['172.31.66.38']
  Community 261: 1 IPs → ['172.31.66.80']
  Community 262: 1 IPs → ['172.31.66.103']
  Community 263: 1 IPs → ['172.31.66.105']
  Community 264: 1 IPs → ['172.31.66.107']
  Community 265: 1 IPs → ['172.31.66.108']
  Community 266: 1 IPs → ['172.31.66.11']
  Community 267: 1 IPs → ['172.31.66.110']
  Community 268: 1 IPs → ['172.31.66.111']
  Community 269: 1 IPs → ['172.31.66.112']
  Community 270: 1 IPs → ['172.31.66.113']
  Community 271: 1 IPs → ['172.31.66.115']
  Community 272: 1 IPs → ['172.31.66.116']
  Community 273: 1 IPs → ['172.31.66.119']
  Community 274: 1 IPs → ['172.31.66.123']
  Community 275: 1 IPs → ['172.31.66.124']
  Community 276: 1 IPs → ['172.31.66.13']
  Community 277: 1 IPs → ['172.31.66.14']
  Community 278: 1 IPs → ['172.31.66.15']
  Community 279: 1 IPs → ['172.31.66.16']
  Community 280: 1 IPs → ['172.31.66.17']
  Community 281: 1 IPs → ['172.31.66.19']
  Community 282: 1 IPs → ['172.31.66.20']
  Community 283: 1 IPs → ['172.31.66.21']
  Community 284: 1 IPs → ['172.31.66.24']
  Community 285: 1 IPs → ['172.31.66.26']
  Community 286: 1 IPs → ['172.31.66.28']
  Community 287: 1 IPs → ['172.31.66.29']
  Community 288: 1 IPs → ['172.31.66.34']
  Community 289: 1 IPs → ['172.31.66.35']
  Community 290: 1 IPs → ['172.31.66.37']
  Community 291: 1 IPs → ['172.31.66.40']
  Community 292: 1 IPs → ['172.31.66.46']
  Community 293: 1 IPs → ['172.31.66.48']
  Community 294: 1 IPs → ['172.31.66.5']
  Community 295: 1 IPs → ['172.31.66.50']
  Community 296: 1 IPs → ['172.31.66.51']
  Community 297: 1 IPs → ['172.31.66.53']
  Community 298: 1 IPs → ['172.31.66.55']
  Community 299: 1 IPs → ['172.31.66.56']
  Community 300: 1 IPs → ['172.31.66.57']
  Community 301: 1 IPs → ['172.31.66.61']
  Community 302: 1 IPs → ['172.31.66.63']
  Community 303: 1 IPs → ['172.31.66.64']
  Community 304: 1 IPs → ['172.31.66.65']
  Community 305: 1 IPs → ['172.31.66.66']
  Community 306: 1 IPs → ['172.31.66.68']
  Community 307: 1 IPs → ['172.31.66.7']
  Community 308: 1 IPs → ['172.31.66.70']
  Community 309: 1 IPs → ['172.31.66.71']
  Community 310: 1 IPs → ['172.31.66.74']
  Community 311: 1 IPs → ['172.31.66.75']
  Community 312: 1 IPs → ['172.31.66.76']
  Community 313: 1 IPs → ['172.31.66.77']
  Community 314: 1 IPs → ['172.31.66.78']
  Community 315: 1 IPs → ['172.31.66.8']
  Community 316: 1 IPs → ['172.31.66.81']
  Community 317: 1 IPs → ['172.31.66.83']
  Community 318: 1 IPs → ['172.31.66.84']
  Community 319: 1 IPs → ['172.31.66.86']
  Community 320: 1 IPs → ['172.31.66.87']
  Community 321: 1 IPs → ['172.31.66.91']
  Community 322: 1 IPs → ['172.31.66.92']
  Community 323: 1 IPs → ['172.31.66.94']
  Community 324: 1 IPs → ['172.31.66.95']
  Community 325: 1 IPs → ['172.31.66.97']
  Community 326: 1 IPs → ['172.31.66.98']
  Community 327: 1 IPs → ['172.31.66.99']
  Community 328: 1 IPs → ['172.31.67.108']
  Community 329: 1 IPs → ['172.31.67.12']
  Community 330: 1 IPs → ['172.31.67.26']
  Community 331: 1 IPs → ['172.31.67.31']
  Community 332: 1 IPs → ['172.31.67.9']
  Community 333: 1 IPs → ['172.31.67.102']
  Community 334: 1 IPs → ['172.31.67.104']
  Community 335: 1 IPs → ['172.31.67.105']
  Community 336: 1 IPs → ['172.31.67.107']
  Community 337: 1 IPs → ['172.31.67.109']
  Community 338: 1 IPs → ['172.31.67.113']
  Community 339: 1 IPs → ['172.31.67.114']
  Community 340: 1 IPs → ['172.31.67.115']
  Community 341: 1 IPs → ['172.31.67.116']
  Community 342: 1 IPs → ['172.31.67.117']
  Community 343: 1 IPs → ['172.31.67.118']
  Community 344: 1 IPs → ['172.31.67.119']
  Community 345: 1 IPs → ['172.31.67.120']
  Community 346: 1 IPs → ['172.31.67.121']
  Community 347: 1 IPs → ['172.31.67.122']
  Community 348: 1 IPs → ['172.31.67.123']
  Community 349: 1 IPs → ['172.31.67.124']
  Community 350: 1 IPs → ['172.31.67.125']
  Community 351: 1 IPs → ['172.31.67.16']
  Community 352: 1 IPs → ['172.31.67.17']
  Community 353: 1 IPs → ['172.31.67.18']
  Community 354: 1 IPs → ['172.31.67.19']
  Community 355: 1 IPs → ['172.31.67.20']
  Community 356: 1 IPs → ['172.31.67.22']
  Community 357: 1 IPs → ['172.31.67.27']
  Community 358: 1 IPs → ['172.31.67.29']
  Community 359: 1 IPs → ['172.31.67.30']
  Community 360: 1 IPs → ['172.31.67.33']
  Community 361: 1 IPs → ['172.31.67.4']
  Community 362: 1 IPs → ['172.31.67.40']
  Community 363: 1 IPs → ['172.31.67.42']
  Community 364: 1 IPs → ['172.31.67.45']
  Community 365: 1 IPs → ['172.31.67.47']
  Community 366: 1 IPs → ['172.31.67.48']
  Community 367: 1 IPs → ['172.31.67.52']
  Community 368: 1 IPs → ['172.31.67.53']
  Community 369: 1 IPs → ['172.31.67.56']
  Community 370: 1 IPs → ['172.31.67.57']
  Community 371: 1 IPs → ['172.31.67.58']
  Community 372: 1 IPs → ['172.31.67.59']
  Community 373: 1 IPs → ['172.31.67.6']
  Community 374: 1 IPs → ['172.31.67.61']
  Community 375: 1 IPs → ['172.31.67.62']
  Community 376: 1 IPs → ['172.31.67.63']
  Community 377: 1 IPs → ['172.31.67.64']
  Community 378: 1 IPs → ['172.31.67.66']
  Community 379: 1 IPs → ['172.31.67.67']
  Community 380: 1 IPs → ['172.31.67.7']
  Community 381: 1 IPs → ['172.31.67.70']
  Community 382: 1 IPs → ['172.31.67.71']
  Community 383: 1 IPs → ['172.31.67.73']
  Community 384: 1 IPs → ['172.31.67.77']
  Community 385: 1 IPs → ['172.31.67.78']
  Community 386: 1 IPs → ['172.31.67.8']
  Community 387: 1 IPs → ['172.31.67.82']
  Community 388: 1 IPs → ['172.31.67.83']
  Community 389: 1 IPs → ['172.31.67.89']
  Community 390: 1 IPs → ['172.31.67.91']
  Community 391: 1 IPs → ['172.31.67.92']
  Community 392: 1 IPs → ['172.31.67.93']
  Community 393: 1 IPs → ['172.31.67.95']
  Community 394: 1 IPs → ['172.31.67.96']
  Community 395: 1 IPs → ['172.31.67.97']
  Community 396: 1 IPs → ['172.31.67.98']
  Community 397: 1 IPs → ['172.31.67.99']
  Community 398: 22 IPs → ['172.31.68.1', '172.31.68.10', '172.31.68.11', '172.31.68.12', '172.31.68.13', '172.31.68.14', '172.31.68.15', '172.31.68.18', '172.31.68.19', '172.31.68.20', '172.31.68.21', '172.31.68.23', '172.31.68.25', '172.31.68.26', '172.31.68.28', '172.31.68.30', '172.31.68.31', '172.31.68.4', '172.31.68.5', '172.31.68.6', '172.31.68.8', '172.31.68.9']
  Community 399: 5 IPs → ['172.31.69.13', '172.31.69.15', '172.31.69.18', '172.31.69.21', '172.31.69.7']

In [10]:
# CROSS-REFERENCE WITH KNOWN IPs FROM DOCUMENTATION
# These are the victim IPs from Table 2
KNOWN_SERVERS = {"172.31.69.25", "172.31.69.28", "172.31.69.24", "172.31.69.13"}
KNOWN_BOT_VICTIMS = {
    "172.31.69.23", "172.31.69.17", "172.31.69.14", "172.31.69.12",
    "172.31.69.10", "172.31.69.8",  "172.31.69.6",  "172.31.69.26",
    "172.31.69.29", "172.31.69.30",
}

print("\n── Anchoring communities to known IPs ──")
for cid, members in sorted(communities.items()):
    member_set = set(members)
    servers_here  = member_set & KNOWN_SERVERS
    bots_here     = member_set & KNOWN_BOT_VICTIMS
    print(f"  Comm {cid}: known_servers={servers_here}, known_bot_victims={bots_here}")

── Anchoring communities to known IPs ──
  Comm 0: known_servers=set(), known_bot_victims=set()
  Comm 1: known_servers=set(), known_bot_victims=set()
  Comm 2: known_servers=set(), known_bot_victims=set()
  Comm 3: known_servers=set(), known_bot_victims=set()
  Comm 4: known_servers=set(), known_bot_victims=set()
  Comm 5: known_servers=set(), known_bot_victims=set()
  Comm 6: known_servers=set(), known_bot_victims=set()
  Comm 7: known_servers=set(), known_bot_victims=set()
  Comm 8: known_servers=set(), known_bot_victims=set()
  Comm 9: known_servers=set(), known_bot_victims=set()
  Comm 10: known_servers=set(), known_bot_victims=set()
  Comm 11: known_servers=set(), known_bot_victims=set()
  Comm 12: known_servers=set(), known_bot_victims=set()
  Comm 13: known_servers=set(), known_bot_victims=set()
  Comm 14: known_servers=set(), known_bot_victims=set()
  Comm 15: known_servers=set(), known_bot_victims=set()
  Comm 16: known_servers=set(), known_bot_victims=set()
  Comm 17: known_servers=set(), known_bot_victims=set()
  Comm 18: known_servers=set(), known_bot_victims=set()
  Comm 19: known_servers=set(), known_bot_victims=set()
  Comm 20: known_servers=set(), known_bot_victims=set()
  Comm 21: known_servers=set(), known_bot_victims=set()
  Comm 22: known_servers=set(), known_bot_victims=set()
  Comm 23: known_servers=set(), known_bot_victims=set()
  Comm 24: known_servers=set(), known_bot_victims=set()
  Comm 25: known_servers=set(), known_bot_victims=set()
  Comm 26: known_servers=set(), known_bot_victims=set()
  Comm 27: known_servers=set(), known_bot_victims=set()
  Comm 28: known_servers=set(), known_bot_victims=set()
  Comm 29: known_servers=set(), known_bot_victims=set()
  Comm 30: known_servers=set(), known_bot_victims=set()
  Comm 31: known_servers=set(), known_bot_victims=set()
  Comm 32: known_servers=set(), known_bot_victims=set()
  Comm 33: known_servers=set(), known_bot_victims=set()
  Comm 34: known_servers=set(), known_bot_victims=set()
  Comm 35: known_servers=set(), known_bot_victims=set()
  Comm 36: known_servers=set(), known_bot_victims=set()
  Comm 37: known_servers=set(), known_bot_victims=set()
  Comm 38: known_servers=set(), known_bot_victims=set()
  Comm 39: known_servers=set(), known_bot_victims=set()
  Comm 40: known_servers=set(), known_bot_victims=set()
  Comm 41: known_servers=set(), known_bot_victims=set()
  Comm 42: known_servers=set(), known_bot_victims=set()
  Comm 43: known_servers=set(), known_bot_victims=set()
  Comm 44: known_servers=set(), known_bot_victims=set()
  Comm 45: known_servers=set(), known_bot_victims=set()
  Comm 46: known_servers=set(), known_bot_victims=set()
  Comm 47: known_servers=set(), known_bot_victims=set()
  Comm 48: known_servers=set(), known_bot_victims=set()
  Comm 49: known_servers=set(), known_bot_victims=set()
  Comm 50: known_servers=set(), known_bot_victims=set()
  Comm 51: known_servers=set(), known_bot_victims=set()
  Comm 52: known_servers=set(), known_bot_victims=set()
  Comm 53: known_servers=set(), known_bot_victims=set()
  Comm 54: known_servers=set(), known_bot_victims=set()
  Comm 55: known_servers=set(), known_bot_victims=set()
  Comm 56: known_servers=set(), known_bot_victims=set()
  Comm 57: known_servers=set(), known_bot_victims=set()
  Comm 58: known_servers=set(), known_bot_victims=set()
  Comm 59: known_servers=set(), known_bot_victims=set()
  Comm 60: known_servers=set(), known_bot_victims=set()
  Comm 61: known_servers=set(), known_bot_victims=set()
  Comm 62: known_servers=set(), known_bot_victims=set()
  Comm 63: known_servers=set(), known_bot_victims=set()
  Comm 64: known_servers=set(), known_bot_victims=set()
  Comm 65: known_servers=set(), known_bot_victims=set()
  Comm 66: known_servers=set(), known_bot_victims=set()
  Comm 67: known_servers=set(), known_bot_victims=set()
  Comm 68: known_servers=set(), known_bot_victims=set()
  Comm 69: known_servers=set(), known_bot_victims=set()
  Comm 70: known_servers=set(), known_bot_victims=set()
  Comm 71: known_servers=set(), known_bot_victims=set()
  Comm 72: known_servers=set(), known_bot_victims=set()
  Comm 73: known_servers=set(), known_bot_victims=set()
  Comm 74: known_servers=set(), known_bot_victims=set()
  Comm 75: known_servers=set(), known_bot_victims=set()
  Comm 76: known_servers=set(), known_bot_victims=set()
  Comm 77: known_servers=set(), known_bot_victims=set()
  Comm 78: known_servers=set(), known_bot_victims=set()
  Comm 79: known_servers=set(), known_bot_victims=set()
  Comm 80: known_servers=set(), known_bot_victims=set()
  Comm 81: known_servers=set(), known_bot_victims=set()
  Comm 82: known_servers=set(), known_bot_victims=set()
  Comm 83: known_servers=set(), known_bot_victims=set()
  Comm 84: known_servers=set(), known_bot_victims=set()
  Comm 85: known_servers=set(), known_bot_victims=set()
  Comm 86: known_servers=set(), known_bot_victims=set()
  Comm 87: known_servers=set(), known_bot_victims=set()
  Comm 88: known_servers=set(), known_bot_victims=set()
  Comm 89: known_servers=set(), known_bot_victims=set()
  Comm 90: known_servers=set(), known_bot_victims=set()
  Comm 91: known_servers=set(), known_bot_victims=set()
  Comm 92: known_servers=set(), known_bot_victims=set()
  Comm 93: known_servers=set(), known_bot_victims=set()
  Comm 94: known_servers=set(), known_bot_victims=set()
  Comm 95: known_servers=set(), known_bot_victims=set()
  Comm 96: known_servers=set(), known_bot_victims=set()
  Comm 97: known_servers=set(), known_bot_victims=set()
  Comm 98: known_servers=set(), known_bot_victims=set()
  Comm 99: known_servers=set(), known_bot_victims=set()
  Comm 100: known_servers=set(), known_bot_victims=set()
  Comm 101: known_servers=set(), known_bot_victims=set()
  Comm 102: known_servers=set(), known_bot_victims=set()
  Comm 103: known_servers=set(), known_bot_victims=set()
  Comm 104: known_servers=set(), known_bot_victims=set()
  Comm 105: known_servers=set(), known_bot_victims=set()
  Comm 106: known_servers=set(), known_bot_victims=set()
  Comm 107: known_servers=set(), known_bot_victims=set()
  Comm 108: known_servers=set(), known_bot_victims=set()
  Comm 109: known_servers=set(), known_bot_victims=set()
  Comm 110: known_servers=set(), known_bot_victims=set()
  Comm 111: known_servers=set(), known_bot_victims=set()
  Comm 112: known_servers=set(), known_bot_victims=set()
  Comm 113: known_servers=set(), known_bot_victims=set()
  Comm 114: known_servers=set(), known_bot_victims=set()
  Comm 115: known_servers=set(), known_bot_victims=set()
  Comm 116: known_servers=set(), known_bot_victims=set()
  Comm 117: known_servers=set(), known_bot_victims=set()
  Comm 118: known_servers=set(), known_bot_victims=set()
  Comm 119: known_servers=set(), known_bot_victims=set()
  Comm 120: known_servers=set(), known_bot_victims=set()
  Comm 121: known_servers=set(), known_bot_victims=set()
  Comm 122: known_servers=set(), known_bot_victims=set()
  Comm 123: known_servers=set(), known_bot_victims=set()
  Comm 124: known_servers={'172.31.69.24'}, known_bot_victims={'172.31.69.10', '172.31.69.8', '172.31.69.23', '172.31.69.6', '172.31.69.12', '172.31.69.17'}
  Comm 125: known_servers={'172.31.69.28', '172.31.69.25'}, known_bot_victims={'172.31.69.30', '172.31.69.26', '172.31.69.29', '172.31.69.14'}
  Comm 126: known_servers=set(), known_bot_victims=set()
  Comm 127: known_servers=set(), known_bot_victims=set()
  Comm 128: known_servers=set(), known_bot_victims=set()
  Comm 129: known_servers=set(), known_bot_victims=set()
  Comm 130: known_servers=set(), known_bot_victims=set()
  Comm 131: known_servers=set(), known_bot_victims=set()
  Comm 132: known_servers=set(), known_bot_victims=set()
  Comm 133: known_servers=set(), known_bot_victims=set()
  Comm 134: known_servers=set(), known_bot_victims=set()
  Comm 135: known_servers=set(), known_bot_victims=set()
  Comm 136: known_servers=set(), known_bot_victims=set()
  Comm 137: known_servers=set(), known_bot_victims=set()
  Comm 138: known_servers=set(), known_bot_victims=set()
  Comm 139: known_servers=set(), known_bot_victims=set()
  Comm 140: known_servers=set(), known_bot_victims=set()
  Comm 141: known_servers=set(), known_bot_victims=set()
  Comm 142: known_servers=set(), known_bot_victims=set()
  Comm 143: known_servers=set(), known_bot_victims=set()
  Comm 144: known_servers=set(), known_bot_victims=set()
  Comm 145: known_servers=set(), known_bot_victims=set()
  Comm 146: known_servers=set(), known_bot_victims=set()
  Comm 147: known_servers=set(), known_bot_victims=set()
  Comm 148: known_servers=set(), known_bot_victims=set()
  Comm 149: known_servers=set(), known_bot_victims=set()
  Comm 150: known_servers=set(), known_bot_victims=set()
  Comm 151: known_servers=set(), known_bot_victims=set()
  Comm 152: known_servers=set(), known_bot_victims=set()
  Comm 153: known_servers=set(), known_bot_victims=set()
  Comm 154: known_servers=set(), known_bot_victims=set()
  Comm 155: known_servers=set(), known_bot_victims=set()
  Comm 156: known_servers=set(), known_bot_victims=set()
  Comm 157: known_servers=set(), known_bot_victims=set()
  Comm 158: known_servers=set(), known_bot_victims=set()
  Comm 159: known_servers=set(), known_bot_victims=set()
  Comm 160: known_servers=set(), known_bot_victims=set()
  Comm 161: known_servers=set(), known_bot_victims=set()
  Comm 162: known_servers=set(), known_bot_victims=set()
  Comm 163: known_servers=set(), known_bot_victims=set()
  Comm 164: known_servers=set(), known_bot_victims=set()
  Comm 165: known_servers=set(), known_bot_victims=set()
  Comm 166: known_servers=set(), known_bot_victims=set()
  Comm 167: known_servers=set(), known_bot_victims=set()
  Comm 168: known_servers=set(), known_bot_victims=set()
  Comm 169: known_servers=set(), known_bot_victims=set()
  Comm 170: known_servers=set(), known_bot_victims=set()
  Comm 171: known_servers=set(), known_bot_victims=set()
  Comm 172: known_servers=set(), known_bot_victims=set()
  Comm 173: known_servers=set(), known_bot_victims=set()
  Comm 174: known_servers=set(), known_bot_victims=set()
  Comm 175: known_servers=set(), known_bot_victims=set()
  Comm 176: known_servers=set(), known_bot_victims=set()
  Comm 177: known_servers=set(), known_bot_victims=set()
  Comm 178: known_servers=set(), known_bot_victims=set()
  Comm 179: known_servers=set(), known_bot_victims=set()
  Comm 180: known_servers=set(), known_bot_victims=set()
  Comm 181: known_servers=set(), known_bot_victims=set()
  Comm 182: known_servers=set(), known_bot_victims=set()
  Comm 183: known_servers=set(), known_bot_victims=set()
  Comm 184: known_servers=set(), known_bot_victims=set()
  Comm 185: known_servers=set(), known_bot_victims=set()
  Comm 186: known_servers=set(), known_bot_victims=set()
  Comm 187: known_servers=set(), known_bot_victims=set()
  Comm 188: known_servers=set(), known_bot_victims=set()
  Comm 189: known_servers=set(), known_bot_victims=set()
  Comm 190: known_servers=set(), known_bot_victims=set()
  Comm 191: known_servers=set(), known_bot_victims=set()
  Comm 192: known_servers=set(), known_bot_victims=set()
  Comm 193: known_servers=set(), known_bot_victims=set()
  Comm 194: known_servers=set(), known_bot_victims=set()
  Comm 195: known_servers=set(), known_bot_victims=set()
  Comm 196: known_servers=set(), known_bot_victims=set()
  Comm 197: known_servers=set(), known_bot_victims=set()
  Comm 198: known_servers=set(), known_bot_victims=set()
  Comm 199: known_servers=set(), known_bot_victims=set()
  Comm 200: known_servers=set(), known_bot_victims=set()
  Comm 201: known_servers=set(), known_bot_victims=set()
  Comm 202: known_servers=set(), known_bot_victims=set()
  Comm 203: known_servers=set(), known_bot_victims=set()
  Comm 204: known_servers=set(), known_bot_victims=set()
  Comm 205: known_servers=set(), known_bot_victims=set()
  Comm 206: known_servers=set(), known_bot_victims=set()
  Comm 207: known_servers=set(), known_bot_victims=set()
  Comm 208: known_servers=set(), known_bot_victims=set()
  Comm 209: known_servers=set(), known_bot_victims=set()
  Comm 210: known_servers=set(), known_bot_victims=set()
  Comm 211: known_servers=set(), known_bot_victims=set()
  Comm 212: known_servers=set(), known_bot_victims=set()
  Comm 213: known_servers=set(), known_bot_victims=set()
  Comm 214: known_servers=set(), known_bot_victims=set()
  Comm 215: known_servers=set(), known_bot_victims=set()
  Comm 216: known_servers=set(), known_bot_victims=set()
  Comm 217: known_servers=set(), known_bot_victims=set()
  Comm 218: known_servers=set(), known_bot_victims=set()
  Comm 219: known_servers=set(), known_bot_victims=set()
  Comm 220: known_servers=set(), known_bot_victims=set()
  Comm 221: known_servers=set(), known_bot_victims=set()
  Comm 222: known_servers=set(), known_bot_victims=set()
  Comm 223: known_servers=set(), known_bot_victims=set()
  Comm 224: known_servers=set(), known_bot_victims=set()
  Comm 225: known_servers=set(), known_bot_victims=set()
  Comm 226: known_servers=set(), known_bot_victims=set()
  Comm 227: known_servers=set(), known_bot_victims=set()
  Comm 228: known_servers=set(), known_bot_victims=set()
  Comm 229: known_servers=set(), known_bot_victims=set()
  Comm 230: known_servers=set(), known_bot_victims=set()
  Comm 231: known_servers=set(), known_bot_victims=set()
  Comm 232: known_servers=set(), known_bot_victims=set()
  Comm 233: known_servers=set(), known_bot_victims=set()
  Comm 234: known_servers=set(), known_bot_victims=set()
  Comm 235: known_servers=set(), known_bot_victims=set()
  Comm 236: known_servers=set(), known_bot_victims=set()
  Comm 237: known_servers=set(), known_bot_victims=set()
  Comm 238: known_servers=set(), known_bot_victims=set()
  Comm 239: known_servers=set(), known_bot_victims=set()
  Comm 240: known_servers=set(), known_bot_victims=set()
  Comm 241: known_servers=set(), known_bot_victims=set()
  Comm 242: known_servers=set(), known_bot_victims=set()
  Comm 243: known_servers=set(), known_bot_victims=set()
  Comm 244: known_servers=set(), known_bot_victims=set()
  Comm 245: known_servers=set(), known_bot_victims=set()
  Comm 246: known_servers=set(), known_bot_victims=set()
  Comm 247: known_servers=set(), known_bot_victims=set()
  Comm 248: known_servers=set(), known_bot_victims=set()
  Comm 249: known_servers=set(), known_bot_victims=set()
  Comm 250: known_servers=set(), known_bot_victims=set()
  Comm 251: known_servers=set(), known_bot_victims=set()
  Comm 252: known_servers=set(), known_bot_victims=set()
  Comm 253: known_servers=set(), known_bot_victims=set()
  Comm 254: known_servers=set(), known_bot_victims=set()
  Comm 255: known_servers=set(), known_bot_victims=set()
  Comm 256: known_servers=set(), known_bot_victims=set()
  Comm 257: known_servers=set(), known_bot_victims=set()
  Comm 258: known_servers=set(), known_bot_victims=set()
  Comm 259: known_servers=set(), known_bot_victims=set()
  Comm 260: known_servers=set(), known_bot_victims=set()
  Comm 261: known_servers=set(), known_bot_victims=set()
  Comm 262: known_servers=set(), known_bot_victims=set()
  Comm 263: known_servers=set(), known_bot_victims=set()
  Comm 264: known_servers=set(), known_bot_victims=set()
  Comm 265: known_servers=set(), known_bot_victims=set()
  Comm 266: known_servers=set(), known_bot_victims=set()
  Comm 267: known_servers=set(), known_bot_victims=set()
  Comm 268: known_servers=set(), known_bot_victims=set()
  Comm 269: known_servers=set(), known_bot_victims=set()
  Comm 270: known_servers=set(), known_bot_victims=set()
  Comm 271: known_servers=set(), known_bot_victims=set()
  Comm 272: known_servers=set(), known_bot_victims=set()
  Comm 273: known_servers=set(), known_bot_victims=set()
  Comm 274: known_servers=set(), known_bot_victims=set()
  Comm 275: known_servers=set(), known_bot_victims=set()
  Comm 276: known_servers=set(), known_bot_victims=set()
  Comm 277: known_servers=set(), known_bot_victims=set()
  Comm 278: known_servers=set(), known_bot_victims=set()
  Comm 279: known_servers=set(), known_bot_victims=set()
  Comm 280: known_servers=set(), known_bot_victims=set()
  Comm 281: known_servers=set(), known_bot_victims=set()
  Comm 282: known_servers=set(), known_bot_victims=set()
  Comm 283: known_servers=set(), known_bot_victims=set()
  Comm 284: known_servers=set(), known_bot_victims=set()
  Comm 285: known_servers=set(), known_bot_victims=set()
  Comm 286: known_servers=set(), known_bot_victims=set()
  Comm 287: known_servers=set(), known_bot_victims=set()
  Comm 288: known_servers=set(), known_bot_victims=set()
  Comm 289: known_servers=set(), known_bot_victims=set()
  Comm 290: known_servers=set(), known_bot_victims=set()
  Comm 291: known_servers=set(), known_bot_victims=set()
  Comm 292: known_servers=set(), known_bot_victims=set()
  Comm 293: known_servers=set(), known_bot_victims=set()
  Comm 294: known_servers=set(), known_bot_victims=set()
  Comm 295: known_servers=set(), known_bot_victims=set()
  Comm 296: known_servers=set(), known_bot_victims=set()
  Comm 297: known_servers=set(), known_bot_victims=set()
  Comm 298: known_servers=set(), known_bot_victims=set()
  Comm 299: known_servers=set(), known_bot_victims=set()
  Comm 300: known_servers=set(), known_bot_victims=set()
  Comm 301: known_servers=set(), known_bot_victims=set()
  Comm 302: known_servers=set(), known_bot_victims=set()
  Comm 303: known_servers=set(), known_bot_victims=set()
  Comm 304: known_servers=set(), known_bot_victims=set()
  Comm 305: known_servers=set(), known_bot_victims=set()
  Comm 306: known_servers=set(), known_bot_victims=set()
  Comm 307: known_servers=set(), known_bot_victims=set()
  Comm 308: known_servers=set(), known_bot_victims=set()
  Comm 309: known_servers=set(), known_bot_victims=set()
  Comm 310: known_servers=set(), known_bot_victims=set()
  Comm 311: known_servers=set(), known_bot_victims=set()
  Comm 312: known_servers=set(), known_bot_victims=set()
  Comm 313: known_servers=set(), known_bot_victims=set()
  Comm 314: known_servers=set(), known_bot_victims=set()
  Comm 315: known_servers=set(), known_bot_victims=set()
  Comm 316: known_servers=set(), known_bot_victims=set()
  Comm 317: known_servers=set(), known_bot_victims=set()
  Comm 318: known_servers=set(), known_bot_victims=set()
  Comm 319: known_servers=set(), known_bot_victims=set()
  Comm 320: known_servers=set(), known_bot_victims=set()
  Comm 321: known_servers=set(), known_bot_victims=set()
  Comm 322: known_servers=set(), known_bot_victims=set()
  Comm 323: known_servers=set(), known_bot_victims=set()
  Comm 324: known_servers=set(), known_bot_victims=set()
  Comm 325: known_servers=set(), known_bot_victims=set()
  Comm 326: known_servers=set(), known_bot_victims=set()
  Comm 327: known_servers=set(), known_bot_victims=set()
  Comm 328: known_servers=set(), known_bot_victims=set()
  Comm 329: known_servers=set(), known_bot_victims=set()
  Comm 330: known_servers=set(), known_bot_victims=set()
  Comm 331: known_servers=set(), known_bot_victims=set()
  Comm 332: known_servers=set(), known_bot_victims=set()
  Comm 333: known_servers=set(), known_bot_victims=set()
  Comm 334: known_servers=set(), known_bot_victims=set()
  Comm 335: known_servers=set(), known_bot_victims=set()
  Comm 336: known_servers=set(), known_bot_victims=set()
  Comm 337: known_servers=set(), known_bot_victims=set()
  Comm 338: known_servers=set(), known_bot_victims=set()
  Comm 339: known_servers=set(), known_bot_victims=set()
  Comm 340: known_servers=set(), known_bot_victims=set()
  Comm 341: known_servers=set(), known_bot_victims=set()
  Comm 342: known_servers=set(), known_bot_victims=set()
  Comm 343: known_servers=set(), known_bot_victims=set()
  Comm 344: known_servers=set(), known_bot_victims=set()
  Comm 345: known_servers=set(), known_bot_victims=set()
  Comm 346: known_servers=set(), known_bot_victims=set()
  Comm 347: known_servers=set(), known_bot_victims=set()

## 4.4 Subnets based partition

In [9]:
import ipaddress

# SUBNET to DEPARTMENT MAP
# Based on the /24 analysis above.
# To distinguish dep1-4, run the TTL check below first, then fill this in.
SUBNET_TO_DEPT = {
    "172.31.64": "dep1",  
    "172.31.65": "dep2",
    "172.31.66": "dep3",
    "172.31.67": "dep4",
    "172.31.68": "dep5",  # confirmed by dense cluster + Linux TTL
    "172.31.69": "servers",      # confirmed by known server IPs
}

def ip_to_subnet(ip: str) -> str:
    """Extract 172.31.X from an IPv4 string."""
    parts = ip.split(".")
    if len(parts) >= 3:
        return f"{parts[0]}.{parts[1]}.{parts[2]}"
    return "unknown"

def assign_department(row) -> str:
    src_subnet = ip_to_subnet(row["IPV4_SRC_ADDR"])
    dst_subnet = ip_to_subnet(row["IPV4_DST_ADDR"])
    # Prefer src subnet; fall back to dst if src is external
    if src_subnet in SUBNET_TO_DEPT:
        return SUBNET_TO_DEPT[src_subnet]
    if dst_subnet in SUBNET_TO_DEPT:
        return SUBNET_TO_DEPT[dst_subnet]
    return "External"


#  ASSIGN DEPARTMENTS TO FULL DATASET
# Use vectorized pandas instead of row-wise apply — much faster on 20M rows
src_subnet = df["IPV4_SRC_ADDR"].str.extract(r"^(\d+\.\d+\.\d+)")[0]
dst_subnet = df["IPV4_DST_ADDR"].str.extract(r"^(\d+\.\d+\.\d+)")[0]

df["Department"] = src_subnet.map(SUBNET_TO_DEPT).fillna(
    dst_subnet.map(SUBNET_TO_DEPT)
).fillna("External")

print(df["Department"].value_counts())

Department
dep1        5122142
dep3        3874680
dep2        3762566
servers     3599637
dep4        2646598
dep5        1001563
External     108343
Name: count, dtype: int64

In [10]:
# Join dep1-4 into a single "internal" department and dep5 into "it" 
df["Department"] = df["Department"].replace({"dep1": "internal", "dep2": "internal", "dep3": "internal", "dep4": "internal", "dep5": "it"})

print(df["Department"].value_counts())

Department
internal    15405986
servers      3599637
it           1001563
External      108343
Name: count, dtype: int64

## 4.5 Data export

In [ ]:
import fastparquet

# Set the % of first rows to save for each department (for testing)
PERCENT_ROWS = 0.2  # Set to None to save all rows

# Get current working directory
curr_path = os.getcwd()
save_dir = os.path.join(curr_path, "fed_clients")
# Change data_analysis in path for datasets
save_dir = save_dir.replace("data_analysis", "datasets")
os.makedirs(save_dir, exist_ok=True)

# SAVE ONE PARQUET PER FEDERATED CLIENT
for dept, group in df.groupby("Department"):
    # If the department is External, skip it (we only want the 5 internal depts + servers)
    if dept == "External":
        print(f"Skipping External department with {len(group):,} rows")
        continue
    # Remove Department column 
    group = group.drop(columns=["Department"])
    # Create folder if it doesn't exist to save the parquet file
    group_size = len(group)
    if PERCENT_ROWS is not None:
        sample_size = int(group_size * PERCENT_ROWS)
        group = group.head(sample_size)
        print(f"{dept}: {group_size:,} rows → sampling {sample_size:,} rows")
    curr_dir = os.path.join(save_dir, dept)
    os.makedirs(curr_dir, exist_ok=True)
    path = os.path.join(curr_dir, f"{dept}.parquet")
    group.to_parquet(path, index=False)
    print(f"  {dept}: {len(group):,} rows → {path}")

Skipping External department with 108,343 rows
internal: 15,405,986 rows → sampling 3,081,197 rows
  internal: 3,081,197 rows → /home/carandp/FL-NIDS/datasets/fed_clients/internal/internal.parquet
it: 1,001,563 rows → sampling 200,312 rows
  it: 200,312 rows → /home/carandp/FL-NIDS/datasets/fed_clients/it/it.parquet
servers: 3,599,637 rows → sampling 719,927 rows
  servers: 719,927 rows → /home/carandp/FL-NIDS/datasets/fed_clients/servers/servers.parquet

:

# 5. New Clients Generation
## 5.1 Clients by attack/day generation

In [3]:
# ── Map date → client ─────────────────────────────────────────────────────────
DAY_TO_CLIENT = {
    # Client 0: Volumetric / credential attacks
    "2018-02-14": "client0",   # FTP+SSH BruteForce
    "2018-02-20": "client0",   # DDoS LOIC
    "2018-03-02": "client0",   # Botnet

    # Client 1: Denial-of-Service family
    "2018-02-15": "client1",   # DoS GoldenEye + Slowloris
    "2018-02-16": "client1",   # DoS SlowHTTPTest + Hulk
    "2018-02-21": "client1",   # DDoS HOIC

    # Client 2: Application-layer / stealthy attacks
    "2018-02-22": "client2",   # Web attacks day 1
    "2018-02-23": "client2",   # Web attacks day 2
    "2018-02-28": "client2",   # Infiltration day 1
    "2018-03-01": "client2",   # Infiltration day 2
}

# ── Extract date and assign client ────────────────────────────────────────────
df["date_str"] = pd.to_datetime(
    df["FLOW_START_MILLISECONDS"], unit="ms"
).dt.strftime("%Y-%m-%d")

df["client"] = df["date_str"].map(DAY_TO_CLIENT)

# Days with no attacks map to benign — distribute them round-robin
# so each client gets roughly equal benign background volume
benign_days = df[df["client"].isna()]["date_str"].unique()
print("Benign-only days to distribute:", sorted(benign_days))

benign_day_assignment = {
    day: f"client{i % 3}" 
    for i, day in enumerate(sorted(benign_days))
}
# Fill nulls using the benign day map
null_mask = df["client"].isna()
df.loc[null_mask, "client"] = df.loc[null_mask, "date_str"].map(
    lambda d: next(
        (v for k, v in benign_day_assignment.items() if k == d), 
        "client0"  # fallback
    )
)

# ── Verify class balance per client ───────────────────────────────────────────
print("\nClass distribution per client:")
print(
    df.groupby("client")["Label"]
    .value_counts(normalize=True)
    .rename("ratio")
    .reset_index()
    .pivot(index="client", columns="Label", values="ratio")
    .round(4)
)

print("\nRow counts per client:")
print(df.groupby("client").size())

Benign-only days to distribute: ['2018-02-27']

Class distribution per client:
Label         0       1
client
client0  0.8153  0.1847
client1  0.7828  0.2172
client2  0.9766  0.0234

Row counts per client:
client
client0    5799886
client1    6162253
client2    8153390
dtype: int64

In [4]:
# ── Subsample to your 20-30% budget, preserving class ratios ──────────────────
SAMPLE_FRACTION = 0.25  # adjust to fit in memory

dfs = []
for client_name, group in df.groupby("client"):
    # Stratified sample — keep same attack/benign ratio as original
    sampled = (
        group.groupby("Label", group_keys=False)
        .sample(frac=SAMPLE_FRACTION, random_state=42)
    )
    dfs.append(sampled)
    print(f"{client_name}: {len(sampled):,} rows")

df_sampled = pd.concat(dfs, ignore_index=True)

client0: 1,449,972 rows
client1: 1,540,564 rows
client2: 2,038,347 rows

In [18]:
df_sampled.head(1)

,FLOW_START_MILLISECONDS,FLOW_END_MILLISECONDS,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,TCP_FLAGS,CLIENT_TCP_FLAGS,SERVER_TCP_FLAGS,FLOW_DURATION_MILLISECONDS,DURATION_IN,DURATION_OUT,MIN_TTL,MAX_TTL,LONGEST_FLOW_PKT,SHORTEST_FLOW_PKT,MIN_IP_PKT_LEN,MAX_IP_PKT_LEN,SRC_TO_DST_SECOND_BYTES,DST_TO_SRC_SECOND_BYTES,RETRANSMITTED_IN_BYTES,RETRANSMITTED_IN_PKTS,RETRANSMITTED_OUT_BYTES,RETRANSMITTED_OUT_PKTS,SRC_TO_DST_AVG_THROUGHPUT,DST_TO_SRC_AVG_THROUGHPUT,NUM_PKTS_UP_TO_128_BYTES,NUM_PKTS_128_TO_256_BYTES,NUM_PKTS_256_TO_512_BYTES,NUM_PKTS_512_TO_1024_BYTES,NUM_PKTS_1024_TO_1514_BYTES,TCP_WIN_MAX_IN,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,SRC_TO_DST_IAT_MIN,SRC_TO_DST_IAT_MAX,SRC_TO_DST_IAT_AVG,SRC_TO_DST_IAT_STDDEV,DST_TO_SRC_IAT_MIN,DST_TO_SRC_IAT_MAX,DST_TO_SRC_IAT_AVG,DST_TO_SRC_IAT_STDDEV,Label,Attack,date_str,client
0,1519150206435,1519150206500,172.31.66.11,52575,74.125.28.99,443,6,91,237,4,40,1,25,25,17,65,65,0,128,128,86,40,40,86,0,3,0,0,0,0,28727,4848,5,0,0,0,0,258,187,0,0,0,0,0,0,0,63,21,29,0,0,0,0,0,Benign,2018-02-20,client0

In [19]:
# Get current working directory
curr_path = os.getcwd()
save_dir = os.path.join(curr_path, "fed_clients")
# Change data_analysis in path for datasets
save_dir = save_dir.replace("data_analysis", "datasets")
os.makedirs(save_dir, exist_ok=True)

# ── Save ──────────────────────────────────────────────────────────────────────
for client_name, group in df_sampled.groupby("client"):
    curr_dir = os.path.join(save_dir, client_name)
    os.makedirs(curr_dir, exist_ok=True)
    path = os.path.join(curr_dir, f"{client_name}.parquet")
    group.to_parquet(path, index=False)
    group.drop(columns=["date_str", "client"]).to_parquet(path, index=False)
    print(f"Saved {path}: {len(group):,} rows")

Saved /home/carandp/FL-NIDS/datasets/fed_clients/client0/client0.parquet: 1,449,972 rows
Saved /home/carandp/FL-NIDS/datasets/fed_clients/client1/client1.parquet: 1,540,564 rows
Saved /home/carandp/FL-NIDS/datasets/fed_clients/client2/client2.parquet: 2,038,347 rows

## 5.2 Centralized csv generation

In [14]:
# Get current working directory
curr_path = os.getcwd()
# Change data_analysis in path for datasets
save_dir = curr_path.replace("data_analysis", "centralized")
save_dir = os.path.join(save_dir, "datasets")
save_dir = os.path.join(save_dir, "NF-CSE-CIC-IDS2018-v3")
os.makedirs(save_dir, exist_ok=True)

# Save the sampled subset as a single centralized file in .csv format without "date_str" and "client" columns
centralized_path = os.path.join(save_dir, "NF-CSE-CIC-IDS2018-v3.csv")
df_sampled.drop(columns=["date_str", "client"]).to_csv(centralized_path, index=False)
print(f"Saved centralized subset: {centralized_path} with {len(df_sampled):,} rows")

Saved centralized subset: /home/carandp/FL-NIDS/centralized/datasets/NF-CSE-CIC-IDS2018-v3/NF-CSE-CIC-IDS2018-v3.csv with 5,028,883 rows